<?php
// display message if set
if (isset($message)) echo "<p>" . htmlspecialchars($message, ENT_QUOTES, 'UTF-8') . "</p>";

// include header (loads translations and theme)
include __DIR__ . '/header.php';
?>

<!DOCTYPE html>
<html lang="<?= htmlspecialchars($_SESSION['lang'] ?? 'en') ?>">
<head>
    <meta charset="UTF-8">
    <title><?= $t['login_title'] ?? 'User Login' ?></title>
    <style>
        /* body style with theme support */
        body {
            font-family: Arial, sans-serif;
            background-color: <?= ($_SESSION['theme'] ?? 'light') === 'dark' ? '#121212' : '#f5f5f5' ?>;
            color: <?= ($_SESSION['theme'] ?? 'light') === 'dark' ? '#fff' : '#000' ?>;
            transition: all 0.3s ease;
            padding: 30px;
        }

        form {
            max-width: 420px;
            margin: 0 auto;
            background: <?= ($_SESSION['theme'] ?? 'light') === 'dark' ? '#1e1e1e' : '#ffffff' ?>;
            padding: 18px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        }

        label { display: block; margin-top: 10px; font-weight: 600; }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 8px 10px;
            margin-top: 6px;
            border-radius: 6px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        .captcha-row { display: flex; align-items: center; gap: 10px; margin-top: 10px; }
        #captcha-canvas { border: 1px solid #ddd; cursor: pointer; }
        #captcha-refresh { padding: 6px 10px; cursor: pointer; border-radius: 6px; border: 1px solid #0078d7; background: transparent; color: #0078d7; }

        button[type="submit"] {
            margin-top: 14px;
            width: 100%;
            padding: 10px;
            background: #0078d7;
            color: white;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            font-size: 1rem;
        }
    </style>
</head>
<body>
<h2 style="text-align:center;"><?= $t['login_header'] ?? 'Login' ?></h2>

<form action="../control/user_control.php" method="post" novalidate>
    <label for="username"><?= $t['username_label'] ?? 'Username' ?></label>
    <input type="text" name="username" id="username" required>

    <label for="password"><?= $t['password_label'] ?? 'Password' ?></label>
    <input type="password" name="password" id="password" required>

    <!-- captcha -->
    <label for="captcha"><?= $t['captcha_label'] ?? 'enter the text from the image' ?></label>
    <div class="captcha-row">
        <canvas id="captcha-canvas" width="150" height="50" title="<?= $t['captcha_click_refresh'] ?? 'click to refresh' ?>"></canvas>
        <button id="captcha-refresh" type="button"><?= $t['refresh'] ?? 'refresh' ?></button>
    </div>

    <!-- visible field that user types (posted as $_POST['captcha']) -->
    <input type="text" name="captcha" id="captcha" placeholder="<?= $t['captcha_placeholder'] ?? 'enter code' ?>" required style="margin-top:8px;">

    <!-- hidden token generated by js (posted as $_POST['captcha_token']) -->
    <input type="hidden" name="captcha_token" id="captcha_token">

    <div style="margin-top:10px; font-size:0.9rem; color:#666;">
        <?= $t['captcha_info'] ?? 'type the characters shown in the image.' ?>
    </div>

    <button type="submit" name="login"><?= $t['login_button'] ?? 'Login' ?></button>
</form>

<p><a href="register_views.php"><?= $t['register_link'] ?? "Don't have an account yet? Create one here." ?></a></p>
<script src="JS/captcha.js"></script>
</body>
</html>
